### ISSUE TITLE
Cant run single InlineAutoMockData tests

### ISSUE THREAD

**Issue by Mech0z** [ObjectivityLtd/AutoFixture.XUnit2.AutoMock#34]
I have this method
```
[Theory]
        [InlineAutoMockData(2019, 1, 1, 0)]
        [InlineAutoMockData(2020, 8, 10, 2)]
        [InlineAutoMockData(2020, 8, 19, 3)]
        [InlineAutoMockData(2020, 8, 20, 4)]
        [InlineAutoMockData(2021, 1, 1, 5)]
        public async Task DeleteOlderThan_WhenCalled_ShouldDeleteFoldersIfOlder(int year, int month, int day, int folderCount, [Frozen]IBlobStorageHelperService blobStorageHelperService, DeleteOldMessagesService sut)
```

If I run it inside Rider/VS with Resharper it shows as 5 different cases
![resharper look](https://user-images.githubusercontent.com/2316684/91965513-db233a00-ed10-11ea-914c-6c5d59f876e5.png)

In Visual studio test runner it shows as a single test with 5 repeats of the same test (It runs it with the correct parameters though)
![vs testrunner](https://user-images.githubusercontent.com/2316684/91965533-e24a4800-ed10-11ea-8117-a0fad4a2c654.png)

But the most problematic is that if I in Rider/R# try to debug a single test, then it will run all 5 tests and not only the single test I selected, debugging 19/8/2020 testcase will first give 1/1/2019 then 10/8/2020 and then the 19/8/2020 I clicked etc

Packages installed:
```
        <PackageReference Include="FluentAssertions" Version="5.10.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.7" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
        <PackageReference Include="NSubstitute" Version="4.2.2" />
        <PackageReference Include="Objectivity.AutoFixture.XUnit2.AutoNSubstitute" Version="3.3.2" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" />
        <PackageReference Include="xunit" Version="2.4.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
```

**Comment by piotrzajac** [comment]
The issue is related to data discovery. In your scenario you provide static data for `int year, int month, int day, int folderCount` however it has to be regenerated for the rest which is `IBlobStorageHelperService blobStorageHelperService, DeleteOldMessagesService sut`.

In other words it means that data generation is triggered for each `InlineAutoMockData` attribute in the order of appearance in the code. Such behavior is in line with `InlineAutoData` attribute from `AutoFixture.XUnit2`.

If such behavior is important for you than I recommend using `InlineData` from xUnit for static data and creating the rest with `Fixture` within method body.
